Émulateur PROCSI: src/breakpoint.h File Reference
src/breakpoint.h File Reference
#include <stdbool.h>
Data Structures
struct breakpoint_t
struct breakpoints_list
Typedefs
typedef struct breakpoint_t breakpoint
Functions
void breakpoint_list_new (breakpoints_list *list)
bool breakpoint_list_has (breakpoints_list *list, unsigned int line)
breakpoint * breakpoint_list_get (breakpoints_list *list, unsigned int index)
bool breakpoint_list_add (breakpoints_list *list, unsigned int line)
bool breakpoint_list_rm (breakpoints_list *list, unsigned int num)
void breakpoint_list_display (breakpoints_list *list)
Typedef Documentation
typedef struct breakpoint_t breakpoint
Function Documentation
bool breakpoint_list_add (breakpoints_list * list, unsigned int line)
Definition at line 41 of file breakpoint.c.
References breakpoint_list_has(), breakpoints_list::count, breakpoints_list::head, breakpoint_t::line, breakpoint_t::next, breakpoint_t::num, and breakpoints_list::size.
Referenced by debugger_start().
void breakpoint_list_display (breakpoints_list * list)
Definition at line 13 of file breakpoint.c.
References breakpoints_list::head, and breakpoint_t::next.
Referenced by debugger_start().
breakpoint* breakpoint_list_get (breakpoints_list * list, unsigned int index)
Definition at line 30 of file breakpoint.c.
References breakpoints_list::head, and breakpoint_t::next.
bool breakpoint_list_has (breakpoints_list * list, unsigned int line)
Definition at line 19 of file breakpoint.c.
References breakpoints_list::head, and breakpoint_t::next.
Referenced by breakpoint_list_add().
void breakpoint_list_new (breakpoints_list * list)
Definition at line 6 of file breakpoint.c.
References breakpoints_list::count, breakpoints_list::head, and breakpoints_list::size.
Referenced by debugger_start().
bool breakpoint_list_rm (breakpoints_list * list, unsigned int num)
Definition at line 65 of file breakpoint.c.
References breakpoints_list::head, breakpoint_t::next, and breakpoints_list::size.
Referenced by debugger_start().