Émulateur PROCSI: src/cmd_word.h File Reference
src/cmd_word.h File Reference
#include "sivm.h"
#include "instructions.h"
Defines
#define MAX_INSTR_PRINT_SIZE 15
Functions
bool getModes (cmd_word *word, mode *destMode, mode *sourceMode)
Define Documentation
#define MAX_INSTR_PRINT_SIZE 15
Maximum length for a string representing a command word in assembly code.
Definition at line 8 of file cmd_word.h.
Referenced by disassemble().
Function Documentation
bool getModes (cmd_word * word, mode * destMode, mode * sourceMode)
Computes the destination and source adressing modes from a command word.
Parameters:
word the command word from which to compute adressing modes
sourceMode pointer to the source mode variable to set
destMode pointer to the destination mode variable to set
Returns:
false if the given modes are illegal
Definition at line 14 of file cmd_word.c.
References cmd_word::codage, DIRECT, DIRIMM, DIRREG, IMMEDIATE, INDIMM, INDIRECT, INDREG, logm(), cmd_word::mode, REGDIR, REGIMM, REGIND, REGISTER, and REGREG.
Referenced by getDestinationParameter(), and getSourceParameter().