Émulateur PROCSI: src/cmd_word.c File Reference
src/cmd_word.c File Reference
#include <stdlib.h>
#include <string.h>
#include "cmd_word.h"
#include "instructions.h"
Functions
bool getModes (cmd_word *word, mode *destMode, mode *sourceMode)
Disassembly
char * appendName (char *string, const cmd_word w)
char * appendParameter (char *string, const cmd_word w, mode m)
char * disassemble (size_t length, const cmd_word words[])
Function Documentation
char* appendName (char * string, const cmd_word w)
Appends the given word's command name at the end of the given string.
Returns:
pointer to the populated string
Definition at line 62 of file cmd_word.c.
References getInstruction().
Referenced by disassemble().
char* appendParameter (char * string, const cmd_word w, mode m)
Appends the given parameter at the end of the given string.
Parameters:
string the string to populate
w the word representing the parameter. If the mode makes the a
Returns:
pointer to the populated string
Definition at line 72 of file cmd_word.c.
References getInstruction().
char* disassemble (size_t length, const cmd_word words[])
Returns a string with the given instructions in assembly form.
Parameters:
length length of the words array
words array of cmd_word to disassemble
Returns:
a string representing words in assembly language
Definition at line 82 of file cmd_word.c.
References appendName(), cmd_word::codage, DIRIMM, DIRREG, INDIMM, INDREG, logm(), MAX_INSTR_PRINT_SIZE, cmd_word::mode, REGDIR, REGIMM, REGIND, and REGREG.
bool getModes (cmd_word * word, mode * destMode, mode * sourceMode)
Computes the destination and source adressing modes from a command word.
Parameters:
word the command word from which to compute adressing modes
sourceMode pointer to the source mode variable to set
destMode pointer to the destination mode variable to set
Returns:
false if the given modes are illegal
Definition at line 14 of file cmd_word.c.
References cmd_word::codage, DIRECT, DIRIMM, DIRREG, IMMEDIATE, INDIMM, INDIRECT, INDREG, logm(), cmd_word::mode, REGDIR, REGIMM, REGIND, REGISTER, and REGREG.
Referenced by getDestinationParameter(), and getSourceParameter().