Émulateur PROCSI: src/debugger.h File Reference
src/debugger.h File Reference
#include "sivm.h"
#include "parser.h"
Data Structures
struct Debugger
Structure for debugging.
Functions
void debugger_new (Debugger *debug)
Initialize a Debugger structure.
void debugger_start (Debugger *debug)
Start the debugger.
Function Documentation
void debugger_new (Debugger * debug)
Initialize a Debugger structure.
Definition at line 82 of file debugger.c.
References quit(), Debugger::sivm, sivm_load(), sivm_new(), and sivm_parse_file().
Referenced by debugger_start(), and main().
void debugger_start (Debugger * debug)
Start the debugger.
Definition at line 127 of file debugger.c.
References BREAKPOINT, breakpoint_list_add(), breakpoint_list_display(), breakpoint_list_new(), breakpoint_list_rm(), debugger_new(), DISPLAY, display_help(), find_command(), HELP, breakpoint_t::line, breakpoint_t::num, QUIT, readLine(), RESTART, RUN, Debugger::sivm, sivm_status(), sivm_step(), STATUS, STEP, and UNKNOWN.
Referenced by main().