Émulateur PROCSI: src/debugger.c File Reference
src/debugger.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <ctype.h>
#include <stdbool.h>
#include "debugger.h"
#include "breakpoint.h"
#include "instructions.h"
#include "util.h"
Data Structures
struct Command
Structure to reference a debugger command.
Defines
#define NB_COMMANDS 8
Enumerations
enum type_command {
RUN = 0, STEP, QUIT, STATUS,
RESTART, HELP, DISPLAY, BREAKPOINT,
UNKNOWN
}
Enumerate all commands.
Functions
int find_command (char *cmd)
find the command in the array of Command
void display_help ()
display all available commands and their help
void debugger_new (Debugger *debug)
Initialize a Debugger structure.
void debugger_start (Debugger *debug)
Start the debugger.
Variables
Command commands [NB_COMMANDS]
Array of available commands.
Define Documentation
#define NB_COMMANDS 8
number of commands
Definition at line 39 of file debugger.c.
Referenced by display_help(), and find_command().
Enumeration Type Documentation
enum type_command
Enumerate all commands.
Enumerator:
RUN
STEP
QUIT
STATUS
RESTART
HELP
DISPLAY
BREAKPOINT
UNKNOWN
Definition at line 26 of file debugger.c.
Function Documentation
void debugger_new (Debugger * debug)
Initialize a Debugger structure.
Definition at line 82 of file debugger.c.
References quit(), Debugger::sivm, sivm_load(), sivm_new(), and sivm_parse_file().
Referenced by debugger_start(), and main().
void debugger_start (Debugger * debug)
Start the debugger.
Definition at line 127 of file debugger.c.
References BREAKPOINT, breakpoint_list_add(), breakpoint_list_display(), breakpoint_list_new(), breakpoint_list_rm(), debugger_new(), DISPLAY, display_help(), find_command(), HELP, breakpoint_t::line, breakpoint_t::num, QUIT, readLine(), RESTART, RUN, Debugger::sivm, sivm_status(), sivm_step(), STATUS, STEP, and UNKNOWN.
Referenced by main().
void display_help ()
display all available commands and their help
See also:
commands
Definition at line 76 of file debugger.c.
References commands, and NB_COMMANDS.
Referenced by debugger_start().
int find_command (char * cmd)
find the command in the array of Command
See also:
Command
comands
Definition at line 62 of file debugger.c.
References commands, NB_COMMANDS, and UNKNOWN.
Referenced by debugger_start().
Variable Documentation
Command commands[NB_COMMANDS]
Initial value:
 {
    [RUN]        = { "run", "run program without step by step" },
    [STEP]       = { "step", "make a step in the program" },
    [QUIT]       = { "quit", "close the debugger" },
    [STATUS]     = { "status", "display registers" },
    [RESTART]    = { "restart", "restart the program" },
    [HELP]       = { "help", "display help" },
    [DISPLAY]    = { "display", "display a variable or a mem" },
    [BREAKPOINT] = { "breakpoint", "put or delete a breakpoint" }
}
Array of available commands.
See also:
Command
Definition at line 45 of file debugger.c.
Referenced by display_help(), and find_command().