Émulateur PROCSI: src/instructions.c File Reference
src/instructions.c File Reference
#include "instructions.h"
#include "util.h"
Functions
bool checkModes (const cmd_word m)
Instr getInstruction (const cmd_word m)
Function Documentation
bool checkModes (const cmd_word m)
Tests a word for adressing modes legality. The whole instruction word is tested, in order to determine whether the adressing modes used in it are legal for the instruction it contains.
Returns:
true if the adressing modes are legal.
Definition at line 152 of file instructions.c.
References cmd_word::codage, getInstruction(), cmd_word::mode, and Instr::modes.
Referenced by parse_pass_line().
Instr getInstruction (const cmd_word m)
Returns the instruction encoded in the given word. This accessor is an interface to the private "instructions" array.
See also:
instructions.h::Instr
Definition at line 161 of file instructions.c.
References cmd_word::codage, and cmd_word::codeop.
Referenced by appendName(), appendParameter(), checkModes(), sivm_exec(), and sivm_get_instruction().
bool instr_add (SIVM * sivm, REG * dest, const cmd_word source)
Emulates the ADD command in the given SIVM.
Returns:
true if the command was successful.
Definition at line 29 of file instructions.c.
References cmd_word::brut, and SIVM::sr.
bool instr_jeq (SIVM * sivm, REG * dest, const cmd_word source)
Emulates the JEQ command in the given SIVM.
See also:
instr_jmp
Definition at line 66 of file instructions.c.
References instr_jmp(), and SIVM::sr.
bool instr_jmp (SIVM * sivm, REG * dest, const cmd_word source)
Emulates the JMP command in the given SIVM. This instruction takes only one parameter above the targeted SIVM, source, but keeps the dest argument for type compatibility. WARNING the argument to use is source and not dest. Argument validity will be checked.
Parameters:
source the adress at which the PC register of the given SIVM should be put at.
Returns:
true if the command was successful, false if the PC argument is out of memory bounds.
Definition at line 53 of file instructions.c.
References cmd_word::brut, logm(), MEMSIZE, and SIVM::pc.
Referenced by instr_jeq().
bool instr_load (SIVM * sivm, REG * dest, const cmd_word source)
Emulates the LOAD command in the given SIVM.
Returns:
true if the command was successful.
Definition at line 11 of file instructions.c.
References cmd_word::brut.
bool instr_mov (SIVM * sivm, REG * dest, const cmd_word source)
Emulates the CALL command in the given SIVM.
See also:
instr_jmpEmulates the MOV command in the given SIVM.
Returns:
true if the command was successful.
Definition at line 117 of file instructions.c.
References cmd_word::brut, and SIVM::sr.
bool instr_pop (SIVM * sivm, REG * dest, const cmd_word source)
Emulates the POP command in the given SIVM.
Returns:
true if the command was successful.
Definition at line 91 of file instructions.c.
References cmd_word::brut, logm(), MEMSIZE, SIVM::sp, and SP_INCR.
bool instr_push (SIVM * sivm, REG * dest, const cmd_word source)
Emulates the PUSH command in the given SIVM.
Returns:
true if the command was successful.
Definition at line 76 of file instructions.c.
References logm(), SIVM::mem, MEMSIZE, SIVM::sp, and SP_INCR.
bool instr_store (SIVM * sivm, REG * dest, const cmd_word source)
Emulates the STR command in the given SIVM.
Returns:
true if the command was successful.
Definition at line 20 of file instructions.c.
References cmd_word::brut.
bool instr_sub (SIVM * sivm, REG * dest, const cmd_word source)
Emulates the SUB command in the given SIVM.
Returns:
true if the command was successful.
Definition at line 39 of file instructions.c.
References cmd_word::brut, and SIVM::sr.
Variable Documentation
Instr instructions[]
Initial value:
 {
        [LOAD] = {instr_load,   FM_REGDIR | FM_REGIMM | FM_REGIND,                              "LOAD"},
        [STORE] = {instr_store, FM_DIRIMM | FM_DIRREG | FM_INDIMM | FM_INDREG,  "STORE"},
        [ADD] = {instr_add,             FM_REGREG | FM_REGIMM | FM_REGDIR | FM_REGIND,  "ADD"},
        [SUB] = {instr_sub,             FM_REGREG | FM_REGIMM | FM_REGDIR | FM_REGIND,  "SUB"},
        [JMP] = {instr_jmp,             FM_REGREG | FM_REGIMM | FM_REGDIR | FM_REGIND,  "JMP"},
        [JEQ] = {instr_jeq,             FM_REGREG | FM_REGIMM | FM_REGDIR | FM_REGIND,  "JEQ"},
        [MOV] = {instr_mov,             FM_REGREG | FM_REGIMM,                                                  "MOV"}
}
Describes all available instructions. This array has keys taken from the "instructions" enum, and its values describe the corresponding instructions, as an array containing :
a pointer to the function emulating the instruction to execute
a bitfield describing which adressing modes are legal for this instruction
The bitfield element is created from bit-to-bit OR operations between all the f_modes enum elements.
See also:
instructions.h::enum instructions
instructions.h::enum f_modes
getInstruction
Definition at line 135 of file instructions.c.