Émulateur PROCSI: src/instructions.h File Reference
src/instructions.h File Reference
#include <stdbool.h>
#include "sivm.h"
#include "util.h"
Data Structures
struct Instr
Enumerations
enum instructions {
LOAD = 0x8, STORE = 0x9, ADD = 0x0, SUB = 0x1,
JMP = 0x2, JEQ = 0x3, CALL = 0x4, RET = 0x5,
PUSH = 0x6, POP = 0x7, MOV = 0xA, HALT = 0xF
}
Adressing modes
enum mode {
REGREG = 0x0, REGIMM = 0x4, REGDIR = 0x8, REGIND = 0xC,
DIRIMM = 0x5, DIRREG = 0x1, INDIMM = 0x6, INDREG = 0x2,
REGISTER, IMMEDIATE, DIRECT, INDIRECT
}
enum f_mode {
FM_REGREG = 1 << REGREG, FM_REGIMM = 1 << REGIMM, FM_REGDIR = 1 << REGDIR, FM_REGIND = 1 << REGIND,
FM_DIRIMM = 1 << DIRIMM, FM_DIRREG = 1 << DIRREG, FM_INDIMM = 1 << INDIMM, FM_INDREG = 1 << INDREG
}
Functions
bool checkModes (const cmd_word m)
Instr getInstruction (const cmd_word m)
Enumeration Type Documentation
enum f_mode
Shifted adressing modes. TODO: move to the implementation file TODO: explain clearly why this is done
Enumerator:
FM_REGREG
FM_REGIMM
FM_REGDIR
FM_REGIND
FM_DIRIMM
FM_DIRREG
FM_INDIMM
FM_INDREG
Definition at line 56 of file instructions.h.
enum instructions
Lists all available instructions. The value of the enum elements are the opcodes for the given instruction. Some values are given according to the A.A. courses documents, others are given arbitrarily.
Enumerator:
LOAD
STORE
ADD
SUB
JMP
JEQ
CALL
RET
PUSH
POP
MOV
HALT
Definition at line 12 of file instructions.h.
enum mode
Lists all available adressing modes. The reference for the values is the document "Description de PROCSI" that was given to us in the A.A. courses. We don't use single-type adressing modes only because it's impossible to achieve storing 5x5 possible combinations in 4 bits. The single-type adressing modes (REGISTER, IMMEDIATE, DIRECT, INDIRECT) are not for public use.
See also:
sivm.c::sivm_exec
Enumerator:
REGREG
REGIMM
REGDIR
REGIND
DIRIMM
DIRREG
INDIMM
INDREG
REGISTER
IMMEDIATE
DIRECT
INDIRECT
Definition at line 36 of file instructions.h.
Function Documentation
bool checkModes (const cmd_word m)
Tests a word for adressing modes legality. The whole instruction word is tested, in order to determine whether the adressing modes used in it are legal for the instruction it contains.
Returns:
true if the adressing modes are legal.
Definition at line 152 of file instructions.c.
References cmd_word::codage, getInstruction(), cmd_word::mode, and Instr::modes.
Referenced by parse_pass_line().
Instr getInstruction (const cmd_word m)
Returns the instruction encoded in the given word. This accessor is an interface to the private "instructions" array.
See also:
instructions.h::Instr
Definition at line 161 of file instructions.c.
References cmd_word::codage, and cmd_word::codeop.
Referenced by appendName(), appendParameter(), checkModes(), sivm_exec(), and sivm_get_instruction().