Émulateur PROCSI: src/parser.h File Reference
src/parser.h File Reference
#include <stdlib.h>
#include <string.h>
#include "sivm.h"
#include "util.h"
#include "instructions.h"
Defines
#define _POSIX_SOURCE
Functions
bool sivm_parse (int *memsize, cmd_word *mem[], char *str)
bool sivm_parse_file (int *memsize, cmd_word *mem[], char *file)
Define Documentation
#define _POSIX_SOURCE
Definition at line 4 of file parser.h.
Function Documentation
bool sivm_parse (int * memsize, cmd_word * mem[], char * str)
Parse a procsi assembly source, and loads it in a virtual machine Since mem is allocated in this function, it's up to you to free it when not needed anymore
See also:
svim_parse_file
Parameters:
sivm a pointer to SIVM structure
str the source code of the program to assemble
Returns:
false if any error occured (stderr is written in consequence with perror), true if the source is assembled and loaded corretly.
Definition at line 684 of file parser.c.
References Parser::mem, Parser::memsize, parse_first_pass(), parse_second_pass(), and Parser::program.
Referenced by sivm_parse_file().
bool sivm_parse_file (int * memsize, cmd_word * mem[], char * file)
Parse a procsi assembly file, and loads it in a virtual machine Since mem is allocated in this function, it's up to you to free it when not needed anymore
See also:
svim_parse
Parameters:
sivm a pointer to SIVM structure
str the filename of the source code
Returns:
false if any error occured (stderr is written in consequence with perror), true if the file is assembled and loaded corretly.
Definition at line 152 of file parser.c.
References sivm_parse().
Referenced by debugger_new().