Émulateur PROCSI: src/parser.c File Reference
src/parser.c File Reference
#include "parser.h"
#include <ctype.h>
Data Structures
struct _LblListElm
struct Parser
Enumerations
enum PMode { PM_REG, PM_IMM, PM_IND, PM_DIR }
Functions
mode pseudomode_to_mode (PMode spmode, PMode dpmode)
bool sivm_parse_file (int *memsize, cmd_word *mem[], char *file)
bool iswhitespace (char c)
int ascii2base (char ascii, int base)
bool parse_number (Parser *parser, int *value, bool modifiable)
bool parse_attrib (Parser *parser, PMode *pmode, int *data, int *reg)
bool parse_1attrib (Parser *parser, cmd_word m[3], unsigned int *instrsize)
bool parse_2attribs (Parser *parser, cmd_word m[3], unsigned int *instrsize)
bool parse_pass_line (Parser *parser, char *line)
bool parse_first_pass (Parser *parser)
bool parse_second_pass (Parser *parser)
bool sivm_parse (int *memsize, cmd_word *mem[], char *str)
Typedef Documentation
typedef struct _LblListElm LblListElm
Chained list of labels Helps the assembleur to remember at which address labels are located. A label is caractised by it's name, and it's address (or pointer)
Definition at line 11 of file parser.c.
Enumeration Type Documentation
enum PMode
Pseudo-modes list Since the parser have to read one instrution's attribute at one, we need to have invidual parameter for theses.
Enumerator:
PM_REG
PM_IMM
PM_IND
PM_DIR
Definition at line 89 of file parser.c.
Function Documentation
int ascii2base (char ascii, int base)
Definition at line 180 of file parser.c.
Referenced by parse_number().
bool iswhitespace (char c)
Definition at line 175 of file parser.c.
Referenced by parse_1attrib(), parse_2attribs(), parse_attrib(), and parse_pass_line().
LblListElm* lbllist_add (LblListElm * head, REG ptr, char * name, size_t len)
Adds a label
Parameters:
head pointer to the head of the list (NULL is empty / no list)
ptr the label's address
name label's name
len len of the label name
Returns:
Address to the new head of list
Definition at line 26 of file parser.c.
References _LblListElm::name, _LblListElm::next, and _LblListElm::pointer.
Referenced by parse_first_pass().
bool lbllist_get (LblListElm * head, char * name, size_t len, REG * pointer)
Pick a label element from the list
Parameters:
head pointer to the head of the list
name label's name
len len of the label name
pointer output pointer to label's address
Returns:
true if element is found and pointer is written. false is no corresponding element found
Definition at line 54 of file parser.c.
References lbllist_next().
Referenced by parse_number().
LblListElm* lbllist_next (LblListElm * current)
Get the next link in the chained list of labels
Parameters:
current pointer to the element you want to get the next one
Returns:
Address of the next element. NULL if end of list
Definition at line 42 of file parser.c.
References _LblListElm::next.
Referenced by lbllist_get().
bool parse_1attrib (Parser * parser, cmd_word m[3], unsigned int * instrsize)
Definition at line 338 of file parser.c.
References cmd_word::brut, cmd_word::codage, Parser::col, Parser::cur, DIRECT, IMMEDIATE, INDIRECT, iswhitespace(), cmd_word::mode, parse_attrib(), PM_DIR, PM_IMM, PM_IND, PM_REG, REGISTER, Parser::row, and cmd_word::source.
Referenced by parse_pass_line().
bool parse_2attribs (Parser * parser, cmd_word m[3], unsigned int * instrsize)
Definition at line 386 of file parser.c.
References cmd_word::brut, cmd_word::codage, Parser::col, Parser::cur, cmd_word::dest, iswhitespace(), cmd_word::mode, parse_attrib(), PM_DIR, PM_IMM, PM_IND, PM_REG, pseudomode_to_mode(), Parser::row, and cmd_word::source.
Referenced by parse_pass_line().
bool parse_attrib (Parser * parser, PMode * pmode, int * data, int * reg)
Parses an instruction attribute
Parameters:
parser pointer to the Parser structure
pmode pointer to the mode
reg pointer to the register number
data pointer to the data (for direct/immediate modes)
Returns:
false if no attrib can be read
Definition at line 256 of file parser.c.
References Parser::col, Parser::cur, iswhitespace(), parse_number(), PM_DIR, PM_IMM, PM_IND, PM_REG, and Parser::row.
Referenced by parse_1attrib(), and parse_2attribs().
bool parse_first_pass (Parser * parser)
Parses a first time the whole source code for branches
Parameters:
parser pointer to the Parser structure
Returns:
false if any error occurs
Definition at line 594 of file parser.c.
References Parser::col, Parser::cur, Parser::labels, lbllist_add(), Parser::mem, Parser::memsize, parse_pass_line(), Parser::pc, Parser::program, and Parser::row.
Referenced by sivm_parse().
bool parse_number (Parser * parser, int * value, bool modifiable)
Parses a number
Parameters:
parser a pointer to the Parser structure
value a pointer to an output int
modifiable tells if the numbers base can be modifier (0xY, Yh)
Returns:
false if no number can be read
Definition at line 202 of file parser.c.
References ascii2base(), Parser::col, Parser::cur, Parser::labels, lbllist_get(), and Parser::row.
Referenced by parse_attrib().
bool parse_pass_line (Parser * parser, char * line)
Definition at line 452 of file parser.c.
References ADD, cmd_word::brut, CALL, checkModes(), cmd_word::codage, cmd_word::codeop, Parser::col, Parser::cur, HALT, iswhitespace(), JEQ, JMP, LOAD, Parser::mem, parse_1attrib(), parse_2attribs(), Parser::pc, POP, PUSH, RET, Parser::row, STORE, and SUB.
Referenced by parse_first_pass(), and parse_second_pass().
bool parse_second_pass (Parser * parser)
Parses a second time the source, to assemble
Parameters:
parser pointer to the Parser structure
Returns:
false if any error occurs
Definition at line 652 of file parser.c.
References Parser::col, Parser::cur, parse_pass_line(), Parser::pc, Parser::program, and Parser::row.
Referenced by sivm_parse().
mode pseudomode_to_mode (PMode spmode, PMode dpmode)
Transforms two pseudo-modes to a complete mode This function is using switches since we cannot base on cutting the mode in two bits
Parameters:
spmode source pseudo-mode
dpmode destination pseudo-mode
See also:
parser.c::enum PMode
instructions.h::enum mode
Returns:
A mode ready to be placed into a mot structure
Definition at line 105 of file parser.c.
References DIRECT, DIRIMM, DIRREG, IMMEDIATE, INDIMM, INDIRECT, INDREG, PM_DIR, PM_IMM, PM_IND, PM_REG, REGDIR, REGIMM, REGIND, REGISTER, and REGREG.
Referenced by parse_2attribs().
bool sivm_parse (int * memsize, cmd_word * mem[], char * str)
Parse a procsi assembly source, and loads it in a virtual machine Since mem is allocated in this function, it's up to you to free it when not needed anymore
See also:
svim_parse_file
Parameters:
sivm a pointer to SIVM structure
str the source code of the program to assemble
Returns:
false if any error occured (stderr is written in consequence with perror), true if the source is assembled and loaded corretly.
Definition at line 684 of file parser.c.
References Parser::mem, Parser::memsize, parse_first_pass(), parse_second_pass(), and Parser::program.
Referenced by sivm_parse_file().
bool sivm_parse_file (int * memsize, cmd_word * mem[], char * file)
Parse a procsi assembly file, and loads it in a virtual machine Since mem is allocated in this function, it's up to you to free it when not needed anymore
See also:
svim_parse
Parameters:
sivm a pointer to SIVM structure
str the filename of the source code
Returns:
false if any error occured (stderr is written in consequence with perror), true if the file is assembled and loaded corretly.
Definition at line 152 of file parser.c.
References sivm_parse().
Referenced by debugger_new().