Émulateur PROCSI: src/sivm.c File Reference
src/sivm.c File Reference
#include "sivm.h"
#include "instructions.h"
#include "cmd_word.h"
Functions
SIVM setup
void sivm_new (SIVM *sivm)
Initializes a new ProcSI virtual machine.
bool sivm_load (SIVM *sivm, int memsize, cmd_word mem[memsize])
SIVM instructions execution
bool increment_PC (SIVM *)
bool sivm_exec (SIVM *, cmd_word *)
bool sivm_step (SIVM *sivm)
REG * getDestinationParameter (SIVM *sivm, cmd_word *word)
cmd_word getSourceParameter (SIVM *sivm, cmd_word *word)
Consistency checks
bool checkMemoryAccess (REG index)
bool checkRegisterAccess (unsigned index)
SIVM status inquiry
void sivm_status (SIVM *sivm)
Instr sivm_get_instruction (SIVM *sivm)
Function Documentation
bool checkMemoryAccess (REG index)
Checks whether the given index is legal for access to the memory.
Returns:
true if the access is legal.
Definition at line 55 of file sivm.c.
References logm(), and MEMSIZE.
Referenced by getDestinationParameter(), getSourceParameter(), increment_PC(), sivm_get_instruction(), and sivm_step().
bool checkRegisterAccess (unsigned index)
Checks whether the given index is legal for access to a register.
Returns:
true if the access is legal.
Definition at line 67 of file sivm.c.
References logm(), and NREGS.
Referenced by getDestinationParameter(), and getSourceParameter().
REG* getDestinationParameter (SIVM * sivm, cmd_word * word)
Computes the destination from a command word. WARNING: updates PC if necessary
Parameters:
sivm the VM in which to get the parameters
word the command word from which to compute parameters
dest pointer to the pointer to the destination parameter
Returns:
a pointer to the destination operand, possibly null if the mode encoded in the given word is illegal
Definition at line 123 of file sivm.c.
References cmd_word::brut, checkMemoryAccess(), checkRegisterAccess(), cmd_word::codage, cmd_word::dest, DIRECT, getModes(), IMMEDIATE, increment_PC(), INDIRECT, logm(), SIVM::mem, SIVM::pc, SIVM::reg, and REGISTER.
Referenced by sivm_exec().
cmd_word getSourceParameter (SIVM * sivm, cmd_word * word)
Computes the source from a command word. WARNING: updates PC if necessary
Parameters:
sivm the VM in which to get the parameters
word the command word from which to compute parameters
source pointer to the source parameter
Returns:
the value of the source operand
Definition at line 159 of file sivm.c.
References cmd_word::brut, checkMemoryAccess(), checkRegisterAccess(), cmd_word::codage, cmd_word::dest, DIRECT, getModes(), HALT, IMMEDIATE, increment_PC(), INDIRECT, logm(), SIVM::mem, SIVM::pc, SIVM::reg, REGISTER, and cmd_word::source.
Referenced by sivm_exec().
bool increment_PC (SIVM * sivm)
Handles PC incrementation for an SIVM. Also checks for PC validity, which is why you shouldn't increment PC by hand.
Returns:
false if PC can't be incremented anymore (ie current PC >= MEMSIZE)
Definition at line 106 of file sivm.c.
References checkMemoryAccess(), logm(), and SIVM::pc.
Referenced by getDestinationParameter(), getSourceParameter(), and sivm_step().
bool sivm_exec (SIVM * sivm, cmd_word * word)
Executes the given word in the given SIVM. Checks for invalid adressing modes. WARNING: may update PC through calls to getSourceParameter and getDestinationParameter.
See also:
getSourceParameter
getDestinationParameter
Returns:
true if the instruction was correctly executed.
Definition at line 195 of file sivm.c.
References Instr::function, getDestinationParameter(), getInstruction(), getSourceParameter(), logm(), and Instr::name.
Referenced by sivm_step().
Instr sivm_get_instruction (SIVM * sivm)
Returns the given SIVM's current instruction.
Definition at line 228 of file sivm.c.
References checkMemoryAccess(), getInstruction(), SIVM::mem, and SIVM::pc.
bool sivm_load (SIVM * sivm, int memsize, cmd_word mem[memsize])
Loads the given program in the given SIVM.
Returns:
false if the SIVM's memory is too small to load the whole program, true if the loading was successful.
Definition at line 33 of file sivm.c.
References SIVM::mem, and MEMSIZE.
Referenced by debugger_new().
void sivm_new (SIVM * sivm)
Initializes a new ProcSI virtual machine.
Initializes an SIVM. Inits PC, SP and SR registers to the values defined in the SIVM.h file. Inits all memory and registers of the SIVM to 0.
Definition at line 13 of file sivm.c.
References cmd_word::brut, logm(), SIVM::mem, MEMSIZE, NREGS, SIVM::pc, PC_START, SIVM::reg, SIVM::sp, SP_INCR, SP_START, SIVM::sr, and SR_START.
Referenced by debugger_new().
void sivm_status (SIVM * sivm)
Prints the given SIVM's registers values.
Definition at line 217 of file sivm.c.
References NREGS, SIVM::pc, SIVM::reg, SIVM::sp, and SIVM::sr.
Referenced by debugger_start().
bool sivm_step (SIVM * sivm)
Executes the next instruction in the given SIVM.
See also:
sivm_exec
increment_PC
Returns:
true if the instruction was correctly executed, false if the SIVM has to stop (whether on HALT instruction or because of a bad instruction).
Definition at line 86 of file sivm.c.
References checkMemoryAccess(), cmd_word::codage, cmd_word::codeop, HALT, increment_PC(), logm(), SIVM::mem, SIVM::pc, and sivm_exec().
Referenced by debugger_start().