Émulateur PROCSI: src/sivm.h File Reference
src/sivm.h File Reference
#include <stdbool.h>
#include <stdint.h>
#include <limits.h>
#include <stdio.h>
#include <string.h>
Data Structures
union cmd_word
struct SIVM
Defines
SIVM parameters
#define NREGS 8
#define MEMSIZE 128
#define PC_START 0
#define SR_START 0
#define SP_START MEMSIZE
#define SP_INCR -1
Typedefs
typedef uint16_t REG
Functions
void sivm_new (SIVM *sivm)
Initializes a new ProcSI virtual machine.
bool sivm_load (SIVM *sivm, int memsize, cmd_word mem[memsize])
bool sivm_step (SIVM *sivm)
void sivm_status (SIVM *sivm)
char * sivm_get_instruction_string (SIVM *sivm)
Define Documentation
#define MEMSIZE 128
Size of an SIVM's memory
Definition at line 18 of file sivm.h.
Referenced by checkMemoryAccess(), instr_jmp(), instr_pop(), instr_push(), sivm_load(), and sivm_new().
#define NREGS 8
Number of registers in an SIVM.
Definition at line 16 of file sivm.h.
Referenced by checkRegisterAccess(), sivm_new(), and sivm_status().
#define PC_START 0
PC index at SIVM startup
Definition at line 20 of file sivm.h.
Referenced by sivm_new().
#define SP_INCR -1
SP incrementation Set it to (+)1 to go through ascending adresses, -1 to go through descending adresses. Standard operation is found by setting SP_START at MEMSIZE and this variable to -1 (descending adresses).
Definition at line 29 of file sivm.h.
Referenced by instr_pop(), instr_push(), and sivm_new().
#define SP_START MEMSIZE
SP index at SIVM startup
Definition at line 24 of file sivm.h.
Referenced by sivm_new().
#define SR_START 0
SR index at SIVM startup
Definition at line 22 of file sivm.h.
Referenced by sivm_new().
Typedef Documentation
typedef uint16_t REG
Definition at line 10 of file sivm.h.
Function Documentation
char* sivm_get_instruction_string (SIVM * sivm)
bool sivm_load (SIVM * sivm, int memsize, cmd_word mem[memsize])
Loads the given program in the given SIVM.
Returns:
false if the SIVM's memory is too small to load the whole program, true if the loading was successful.
Definition at line 33 of file sivm.c.
References SIVM::mem, and MEMSIZE.
Referenced by debugger_new().
void sivm_new (SIVM * sivm)
Initializes a new ProcSI virtual machine.
Author:
Me
Initializes an SIVM. Inits PC, SP and SR registers to the values defined in the SIVM.h file. Inits all memory and registers of the SIVM to 0.
Definition at line 13 of file sivm.c.
References cmd_word::brut, logm(), SIVM::mem, MEMSIZE, NREGS, SIVM::pc, PC_START, SIVM::reg, SIVM::sp, SP_INCR, SP_START, SIVM::sr, and SR_START.
Referenced by debugger_new().
void sivm_status (SIVM * sivm)
Prints the given SIVM's registers values.
Definition at line 217 of file sivm.c.
References NREGS, SIVM::pc, SIVM::reg, SIVM::sp, and SIVM::sr.
Referenced by debugger_start().
bool sivm_step (SIVM * sivm)
Executes the next instruction in the given SIVM.
See also:
sivm_exec
increment_PC
Returns:
true if the instruction was correctly executed, false if the SIVM has to stop (whether on HALT instruction or because of a bad instruction).
Definition at line 86 of file sivm.c.
References checkMemoryAccess(), cmd_word::codage, cmd_word::codeop, HALT, increment_PC(), logm(), SIVM::mem, SIVM::pc, and sivm_exec().
Referenced by debugger_start().