Émulateur PROCSI: src/util.h File Reference
src/util.h File Reference
#include <stdbool.h>
#include <string.h>
Defines
Logging levels
Defines the level of verbosity of the program. 0 is the less verbose mode (displays fatal errors only).
#define ERR_LOG_LEVEL 5
#define OUT_LOG_LEVEL 5
Functions
void quit (char *msg)
bool readLine (char *str, size_t length)
void logm (char *msg, char level)
Define Documentation
#define ERR_LOG_LEVEL 5
Maximum level of messages to be displayed to stderr
Definition at line 13 of file util.h.
Referenced by logm().
#define OUT_LOG_LEVEL 5
Maximum level of messages to be displayed to stdout
Definition at line 15 of file util.h.
Referenced by logm().
Function Documentation
void logm (char * msg, char level)
Logs debugging messages.
Parameters:
msg the message to log
level the priority level of the message ; maximum priority is 0, and should be used for fatal errors only.
See also:
ERR_LOG_LEVEL
OUT_LOG_LEVEL
Definition at line 28 of file util.c.
References ERR_LOG_LEVEL, and OUT_LOG_LEVEL.
Referenced by checkMemoryAccess(), checkRegisterAccess(), disassemble(), getDestinationParameter(), getModes(), getSourceParameter(), increment_PC(), instr_jmp(), instr_pop(), instr_push(), sivm_exec(), sivm_new(), and sivm_step().
void quit (char * msg)
Quit the programe with an error
Parameters:
msg the error message
Definition at line 6 of file util.c.
Referenced by debugger_new().
bool readLine (char * str, size_t length)
Read a line from the standard input
Parameters:
str pointer to the string
length size of the maximum input
Returns:
Definition at line 12 of file util.c.
Referenced by debugger_start().