Émulateur PROCSI: src/util.c File Reference
src/util.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include "util.h"
Functions
void quit (char *msg)
bool readLine (char *str, size_t length)
void logm (char *msg, char level)
Function Documentation
void logm (char * msg, char level)
Logs debugging messages.
Parameters:
msg the message to log
level the priority level of the message ; maximum priority is 0, and should be used for fatal errors only.
See also:
ERR_LOG_LEVEL
OUT_LOG_LEVEL
Definition at line 28 of file util.c.
References ERR_LOG_LEVEL, and OUT_LOG_LEVEL.
Referenced by checkMemoryAccess(), checkRegisterAccess(), disassemble(), getDestinationParameter(), getModes(), getSourceParameter(), increment_PC(), instr_jmp(), instr_pop(), instr_push(), sivm_exec(), sivm_new(), and sivm_step().
void quit (char * msg)
Quit the programe with an error
Parameters:
msg the error message
Definition at line 6 of file util.c.
Referenced by debugger_new().
bool readLine (char * str, size_t length)
Read a line from the standard input
Parameters:
str pointer to the string
length size of the maximum input
Returns:
Definition at line 12 of file util.c.
Referenced by debugger_start().